# sed -i "s/IMAGE1/${DOCKERHUB_USER}\/${IMAGE_NAME}:${IMAGE_VERSION}/g" Deployment.yaml
echo ${IMAGE_USER}
echo ${IMAGE_NAME}
echo ${IMAGE_VERSION}
echo "A MINHA IMAGEM CHAMA ${IMAGE_USER}${IMAGE_NAME}:${IMAGE_VERSION} "