---
- hosts: docker
  remote_user: root
  tasks:
   - name: ansible create directory example
     file:
       path: /tmp/devops_directory
       state: directory
       mode: 0755
       recurse: yes
      
   - name: create file
     file:
        path: /tmp/devops_directory/teste
        state: touch
        
  - name: Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
    copy:
      src: $WORKSPACE/kubernetes/Deployment.yaml
      dest: /tmp/devops_directory/Deployment.yaml
      owner: root
      group: root
      mode: 0644