---
- hosts: docker
  tasks:
   - name: create directory
     file:
       path: /tmp/devops_directory
       state: directory
       mode: 0640

   - name: copy file
     copy:
        src: /$WORKSPACE/kubernetes/Deployment.yaml
        dest: /tmp/devops_directory/
