---
- hosts: docker
  tasks:
   - name: create directory
     file:
       path: /tmp/devops_directory
       state: directory
       mode: 0755
       recurse: yes
      
   - name: copy file
     copy:
        src: /kubernetes/Deployment.yaml
        dest: /tmp/devops_directory/
        remote_src: yes