---
- hosts: docker
  remote_user: root
  tasks:
   - name: ansible create directory example
     file:
       path: /tmp/devops_directory
       state: directory
       mode: 0755
       recurse: yes
      
   - name: create file
     file:
        path: /tmp/devops_directory/teste
        state: touch

   - name: copy deployment
     copy:
        src: /kubernetes/Deployment.yaml
        dest: /tmp/devops_directory/Deployment.yaml
